config:
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master-hl
        Logstash_Format On
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
