config:
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host opensearch-cluster-master
        Logstash_Format On
        Retry_Limit False
        Trace_Error     On
        Suppress_Type_Name On
        Replace_Dots On
        HTTP_User admin
        HTTP_Passwd admin
        tls On
        tls.verify Off

    [OUTPUT]
        Name es
        Match host.*
        Host opensearch-cluster-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Suppress_Type_Name On
        Replace_Dots On
        HTTP_User admin
        HTTP_Passwd admin
        tls On
        tls.verify Off

