datasources:
  secretDefinition:
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.prometheus.svc
        editable: false
      - name: Loki
        type: loki
        access: proxy
        url: http://grafana-loki-querier.logging.svc:3100
        editable: false

