{
 "title": "Pod overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_working_set_bytes,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({namespace=~\"$namespace\", pod=~\"$pod\"} |= ``[$__interval]))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\"} |= `` | label_format level=detected_level"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace!=\"\", container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace!=\"\", container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage space",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!=\"tmpfs\"}",
     "legendFormat": "Free space: {{device}} - {{fstype}} - {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype!=\"tmpfs\"}",
     "legendFormat": "Total size: {{device}} - {{fstype}} - {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype!=\"tmpfs\"} - node_filesystem_avail_bytes{fstype!=\"tmpfs\"}",
     "legendFormat": "Used space: {{device}} - {{fstype}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Usage Recived",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"}[3m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Usage Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"}[3m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingress paths",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "kube_ingress_path{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}